# stage 1
FROM node:14.17.6-slim AS base 

WORKDIR /base 

COPY src/package.json ./

RUN npm install 

# stage 2

FROM gcr.io/distroless/nodejs:16

WORKDIR /app

COPY src ./src

COPY --from=base /base/node_modules ./node_modules

EXPOSE 8000